package main;

public enum Types {
    OPAREN, CPAREN, OBRACKET, CBRACKET, OBRACE, CBRACE,

    HASHTAG, TILDE, AT,

    MINUS, PLUS, TIMES, DIVIDE, MODULO,

    EQUALS, NOT, GREATERTHAN, LESSTHAN,

    NUMBER, FNUMBER, STRING, KEY, BOOL,

    IF, WHILE,

    COMMENT,

    END_OF_INPUT, UNKNOWN
}
